[Xorg_util_macros]
git-tree-sha1 = "3b2599117009a2e40f47144bc19eed4dd16e0e7b"

    [[Xorg_util_macros.download]]
    sha256 = "bf95da36f6d96daef2f55214447b3a0559117bf47cb7f9f9bbe46ceba3c003c4"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_util_macros_jll.jl/releases/download/Xorg_util_macros-v1.19.2+2/Xorg_util_macros.v1.19.2.any.tar.gz"
